---
title: "Input Data Metrics"
author: "Pranav Anbarasu"
format:
  html:
    embed-resources: true
    toc: true
    smooth-scroll: true
execute:
  echo: false
---

## Count of Unique Participants

```{r}
#| echo: false
n_unique_pids_adult <- 
  pids_enroll_adults %>% 
  select(ParticipantIdentifier, EnrollmentDate) %>% 
  mutate(EnrollmentDate = lubridate::date(EnrollmentDate)) %>% 
  distinct()
n_unique_pids_adult
```

```{r}
glue::glue('n = {n_unique_pids_adult$ParticipantIdentifier %>% n_distinct()} unique participants enrolled as of {n_unique_pids_adult$EnrollmentDate %>% max()}')
```

## Count of Records

A record corresponds to a single json object (data point/measurement)

```{r}
#| echo: false
nrecs_date_adults %>% arrange(ExportStartDate)
```

## Unique Devices

For the adult cohort, the following device info is extracted from the FitbitDevices files.

```{r}
devices_summary_adult <- 
  devices_adults %>% 
  select(ParticipantIdentifier, Device, Type) %>% 
  group_by(Device, Type) %>% 
  summarise(n_participants = n_distinct(ParticipantIdentifier), )
devices_summary_adult
```

```{r}
glue::glue('n = {devices_summary_adult$n_participants %>% sum()} participants sharing device data via Fitbit as of {devices_adults$Date %>% as.Date() %>% max()}')
```

